server:
  port: 8080

spring:
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  application:
    name: libraryapp

springdoc:
  api-docs:
    enabled: true
  show-actuator: true
  override-with-generic-response: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true