apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: default
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: DS_PROMETHEUS
        uid: prometheusdatasource
        type: prometheus
        access: proxy
        url: http://prometheus-service.default.svc.cluster.local:9090    # ✔
        isDefault: true