apiVersion: v1
kind: ConfigMap
metadata:
  name: libraryapp-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-0.postgres.default.svc.cluster.local:5432/librarydb
  SERVER_HOST: libraryapp-service.default.svc.cluster.local
  SERVER_PORT: "8080"