apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 90s
      evaluation_interval: 90s

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['prometheus-service.default.svc.cluster.local:9090']

      - job_name: 'Spring Boot Application input'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 2s
        static_configs:
          - targets: ['libraryapp-service.default.svc.cluster.local:8080']
            labels:
              application: 'libraryapp'